name: test
on: workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wjmolina/dp-hackathon-2023@main
        with:
          path: package
          name: hello-world
          version: 1.0.0
