name: upload
on:
  push:
    branches:
      - main
jobs:
  job:
    defaults:
      run:
        working-directory: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          python -m pip install --upgrade pip
          pip install wheel twine
      - run: |
          python setup.py sdist bdist_wheel
      - uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read
          source: dist/
          dest: s3://dp-hackathon-2023/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
