name: upload
on: workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      DIR: package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          python -m pip install --upgrade pip
          pip install wheel twine
      - run: |
          python ${{ env.DIR }}/setup.py sdist bdist_wheel
      - uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_S3_BUCKET: dp-hackathon-2023
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "${{ env.DIR }}/dist"
